=== bpirvali-zz/RISK_20/BRERuleData/src/main/resources/RuleDataQueries.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="queryType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="name" use="required" />
				<xs:attribute type="xs:string" name="dbConnection" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="spcallType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="name" use="required" />
				<xs:attribute type="xs:string" name="dbConnection" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="ruledataType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="key" use="required" />
				<xs:attribute type="xs:string" name="query" use="optional" />
				<xs:attribute type="xs:string" name="spcall" use="optional" />
				<xs:attribute type="xs:string" name="column" use="required" />
				<xs:attribute type="xs:string" name="type" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:element name="RuleDataQueries">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="query" maxOccurs="unbounded" minOccurs="0"  type="queryType" />
				<xs:element name="spcall" maxOccurs="unbounded" minOccurs="0"  type="spcallType" />
				<xs:element name="ruledata" maxOccurs="unbounded" minOccurs="0" type="ruledataType" />
			</xs:sequence>
		</xs:complexType>

		<xs:key name="PK_Query_Name">
			<xs:selector xpath=".//query" />
			<xs:field xpath="@name" />
		</xs:key>
		<xs:key name="PK_Spcall_Name">
			<xs:selector xpath=".//spcall" />
			<xs:field xpath="@name" />
		</xs:key>
		<xs:key name="PK_RuleData_Key">
			<xs:selector xpath=".//ruledata" />
			<xs:field xpath="@key" />
		</xs:key>
		<xs:keyref name="FK_QueryRuleData" refer="PK_Query_Name">
			<xs:selector xpath=".//ruledata" />
			<xs:field xpath="@query" />
		</xs:keyref>
		<xs:keyref name="FK_SpcallRuleData" refer="PK_Spcall_Name">
			<xs:selector xpath=".//ruledata" />
			<xs:field xpath="@spcall" />
		</xs:keyref>

	</xs:element>

</xs:schema>

=== bpirvali-zz/RISK_20/BRERuleData/src/test/resources/BadRuleDataQueries1.xml
<?xml version="1.0" encoding="UTF-8"?>

<RuleDataQueries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:schemaLocation="http://www.example.org/RuleDataQueries RuleDataQueries.xsd">

	<query name="query.TestQuery" dbConnection="MSSQL">
		<![CDATA[
			select BATCHDATE, TESTSTRING, TESTINT, TESTREAL, TESTDATE from TESTTABLE
			where ACCOUNTNUM = '[MA_NUM]'
			and BATCHDATE = '[BCD]';
		]]>
	</query>
	
	<spcall name="spcall.TestSP" dbConnection="MSSQL">
		<![CDATA[
			{CALL usp_BRE_AGG_CREDIT('[MA_NUM]', 'TRAN', 'SUM', 120, 'DAY', 'CreditTotal', '[BCD]')}
		]]>
	</spcall>	

	<ruledata key="test.string" query="query.TestQuery" column="TESTSTRING" type="string" />
	<ruledata key="test.int" query="query.TestQuery" column="TESTINT" type="integer" />
	<ruledata key="test.long" query="query.TestQuery" column="TESTINT" type="long" />
	<ruledata key="test.double" query="query.TestQuery" column="TESTREAL" type="double" />
	<ruledata key="test.date" query="query.TestQuery" column="TESTDATE" type="date" />
	
	<ruledata key="testsp.string" spcall="spcall.TestSP" column="CardType" type="string" />
  	<ruledata key="testsp.SalesCount120Day" spcall="spcall.TestSP" column="SALE_CNT" type="integer" />
  	
  	<!-- The problem is here (keyx) -->
  	<ruledata keyx="testsp.SalesAmount120Day" spcall="spcall.TestSP" column="SALE_AMT" type="double" />

</RuleDataQueries>

=== bpirvali-zz/RISK_20/BRERuleData/src/test/resources/TestRuleDataQueries2.xml
<?xml version="1.0" encoding="UTF-8"?>

<RuleDataQueries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:schemaLocation="http://www.example.org/RuleDataQueries RuleDataQueries.xsd">

	<query name="query.TestQuery" dbConnection="MSSQL">
		<![CDATA[
			select BATCHDATE, TESTSTRING, TESTINT, TESTREAL, TESTDATE, TESTBIGINT from TESTTABLE
			where ACCOUNTNUM = '[MA_NUM]'
			and BATCHDATE = '[BCD]'
		]]>
	</query>
	
	<query name="query.ConvTestQuery" dbConnection="MSSQL">
		<![CDATA[
			select BATCHDATE, TESTSTRING, TESTINT, TESTREAL, TESTDATE, TESTBIGINT from TESTTABLE
			where ACCOUNTNUM = '[MA_NUM]'
			and BATCHDATE = '[BCD]'
		]]>
	</query>
		
	<spcall name="spcall.TestSP" dbConnection="MSSQL">
		<![CDATA[
			{CALL usp_BRE_AGG_CREDIT('[MA_NUM]', 'TRAN', 'SUM', 120, 'DAY', 'CreditTotal', '[BCD]')}
		]]>
	</spcall>	

	<ruledata key="test.string" query="query.TestQuery" column="TESTSTRING" type="string" />
	<ruledata key="test.int" query="query.TestQuery" column="TESTINT" type="integer" />
	<ruledata key="test.long" query="query.TestQuery" column="TESTBIGINT" type="long" />
	<ruledata key="test.double" query="query.TestQuery" column="TESTREAL" type="double" />
	<ruledata key="test.date" query="query.TestQuery" column="TESTDATE" type="date" />
	
	<ruledata key="testsp.string" spcall="spcall.TestSP" column="CardType" type="string" />
  	<ruledata key="testsp.SalesCount120Day" spcall="spcall.TestSP" column="SALE_CNT" type="integer" />
  	<ruledata key="testsp.SalesAmount120Day" spcall="spcall.TestSP" column="SALE_AMT" type="double" />

	<!-- converting to integer -->

	<ruledata key="conv.testint1" query="query.ConvTestQuery" column="TESTSTRING" type="integer" />
	<ruledata key="conv.testint2" query="query.ConvTestQuery" column="TESTINT" type="integer" />
	<ruledata key="conv.testint3" query="query.ConvTestQuery" column="TESTBIGINT" type="integer" />
	<ruledata key="conv.testint4" query="query.ConvTestQuery" column="TESTREAL" type="integer" />

	<!-- converting to double -->

	<ruledata key="conv.testdouble1" query="query.ConvTestQuery" column="TESTSTRING" type="double" />
	<ruledata key="conv.testdouble2" query="query.ConvTestQuery" column="TESTINT" type="double" />
	<ruledata key="conv.testdouble3" query="query.ConvTestQuery" column="TESTBIGINT" type="double" />
	<ruledata key="conv.testdouble4" query="query.ConvTestQuery" column="TESTREAL" type="double" />

	<!-- converting to long -->

	<ruledata key="conv.testlong1" query="query.ConvTestQuery" column="TESTSTRING" type="long" />
	<ruledata key="conv.testlong2" query="query.ConvTestQuery" column="TESTINT" type="long" />
	<ruledata key="conv.testlong3" query="query.ConvTestQuery" column="TESTBIGINT" type="long" />
	<ruledata key="conv.testlong4" query="query.ConvTestQuery" column="TESTREAL" type="long" />

	<!-- converting to string -->

	<ruledata key="conv.teststr1" query="query.ConvTestQuery" column="TESTSTRING" type="string" />
	<ruledata key="conv.teststr2" query="query.ConvTestQuery" column="TESTINT" type="string" />
	<ruledata key="conv.teststr3" query="query.ConvTestQuery" column="TESTBIGINT" type="string" />
	<ruledata key="conv.teststr4" query="query.ConvTestQuery" column="TESTREAL" type="string" />
	
</RuleDataQueries>

=== bpirvali-zz/RISK_20/BRERuleData/src/test/resources/TestRuleDataQueries.xml
<?xml version="1.0" encoding="UTF-8"?>

<RuleDataQueries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:schemaLocation="http://www.example.org/RuleDataQueries RuleDataQueries.xsd">

	<query name="query.AggDaily" dbConnection="MSSQL">
		<![CDATA[
			select 1 as DepositCountDaily
		]]>
	</query>
	
	<query name="query.MerchantProfile" dbConnection="MSSQL">
		<![CDATA[
			select 'OPEN' as AccountStatus
		]]>
	</query>
	
	<spcall name="storedproc.120day.tran.credittotal" dbConnection="MSSQL">
		<![CDATA[
			{CALL dbo.usp_BRE_AGG_CREDIT('[MA_NUM]', 'TRAN', 'SUM', 120, 'DAY', 'CreditTotal', '[BCD]')}
		]]>
	</spcall>	
		
	<ruledata key="aggregates.DepositCountDaily" query="query.AggDaily" column="DepositCountDaily" type="double" />
	<ruledata key="merchantProfile.AccountStatus" query="query.MerchantProfile" column="AccountStatus" type="string" />
  	<ruledata key="aggregates.SalesCount120Day" spcall="storedproc.120day.tran.credittotal" column="SALE_CNT" type="long" />
  	<ruledata key="aggregates.SalesAmount120Day" spcall="storedproc.120day.tran.credittotal" column="SALE_AMT" type="long" />

</RuleDataQueries>
